/* Code generated by TDDT4IoTS 
 Date:  Mon Apr 22 2024 */ 
 #include <ESP8266WiFi.h>
/*Reemplaza con tus datos de red*/
const char* ssid = "TU_SSID";
const char* password = "TU_PASSWORD";

/*Configura la dirección IP del servidor al que quieres enviar datos*/
const char* host = "192.168.1.100"; /*O la URL del servidor*/

void setup () { 
  Serial.begin(115200);
  setupWifi();
}
void loop() {
  
} 
void setupWifi() {
  delay(10);
  /*Nos conectamos a nuestra red WiFi*/
  Serial.println();
  Serial.print("Conectando a ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi conectado");
  Serial.println("Dirección IP: ");
  Serial.println(WiFi.localIP());
}