/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.awt.*;
import comunicacionserial.ComunicacionSerial_Arduino;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortList;
import ses.Dao;
import socks.WsCliente;
import utiles.BrowserClass;
import utiles.DataStatic;
import utiles.ScopeApp;
import utiles.UtilDesktop;

/**
 *
 * @author tonyp
 */
public class InitForm extends javax.swing.JFrame {

    private int x, y;
    private String email = "";
    WsCliente ws = null;

    ComunicacionSerial_Arduino ard_cnn = null;
    SerialPortEventListener ard_listen = null;

    /**
     * Creates new form Login
     */
    public InitForm() {
        initComponents();
        init_myconfig();

//        new rojerusan.RSNotifyAnimated("Conectado", "Conexión establecida con éxito", 7,
//                RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft,
//                RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
//        
//        RSNotifyAnimated notify = new rojerusan.RSNotifyAnimated("Saludos", "Bienvenido a la aplicación", Color.orange, Color.white, 
//                Color.magenta, 7, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, 
//                RSNotifyAnimated.TypeNotify.INFORMATION);
//        ((ActionEvent e) -> {
//                String direccion = "https://www.youtube.com/watch?v=Babk3WeJcY4";
//            });
//        notify.setVisible(true);
    }

    public void init_myconfig() {
        this.setLocationRelativeTo(null);
        //AWTUtilities.setWindowOpaque(this, false);

        cargaricono("src/resources/img/logoTdd.png");
//        pan_minlogin.setBackground(new Color(0, 0, 0, 50));

    }

    public void loadData() {
        if (ScopeApp.getDataUser() != null) {
            LblUserName.setText(ScopeApp.getDataUser().getName_person());
            LblUserLastName.setText(ScopeApp.getDataUser().getLastname_person());
            LblUserEmail.setText(ScopeApp.getDataUser().getEmail_person());

            String rol = ScopeApp.getDataUser().getType_person();
            if (rol.equals("U")) {
                rol = "User";
                LblUserRol.setBackground(new Color(26, 188, 156, 255));
            } else if (rol.equals("A")) {
                rol = "Administrator";
                LblUserRol.setBackground(new Color(241, 196, 15, 255));
            } else if (rol.equals("R")) {
                rol = "Root";
                LblUserRol.setBackground(new Color(231, 76, 60, 255));
            } else {
                rol = "Unknow";
                LblUserRol.setBackground(new Color(149, 165, 166, 255));
            }
            LblUserRol.setText(rol);

            System.out.println(ScopeApp.getDataUser().getPathimg_person());
            Image userImg = BrowserClass.cargarImagenDeInternet(ScopeApp.getDataUser().getPathimg_person(), 50, 50);
            if (userImg != null) {
                LblUserImage.setIcon(new ImageIcon(userImg));
            } else {
                LblUserImage.setIcon(new ImageIcon(getImageFromPath("src/resources/img/user.png", 50)));
            }
        } else {
            panUserInfo.setVisible(false);
        }
        String osName = UtilDesktop.getNameOS();
        LblDevSoName.setText(osName);
        LblDevPcName.setText("Name: " + UtilDesktop.getPcName());
        LblDevUserName.setText("User: " + UtilDesktop.getUserPc());

        String source = "settings";
        osName = osName.toLowerCase();
        if (osName.contains("windows")) {
            source = "windows";
        } else if (osName.contains("linux")) {
            source = "linux";
        } else if (osName.contains("mac")) {
            source = "macos";
        }
        try {
            LblDevSOlogo.setIcon(new ImageIcon(getImageFromPath("resources/img/" + source + ".png", 50)));
        } catch (Exception e) {
            System.out.println("err:" + e.getMessage());
        }

    }

    private Image getImageFromPath(String direccion, int size) {
        ImageIcon im = new ImageIcon(direccion);
        Image img = im.getImage();
        return img.getScaledInstance(size, size, Image.SCALE_AREA_AVERAGING);
    }

    private void cargaricono(String direccion) {
        ImageIcon im = new ImageIcon(direccion);
        Image img = im.getImage();
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_tittle = new javax.swing.JPanel();
        btnclose = new RSMaterialComponent.RSButtonIconTwo();
        btnminimize = new RSMaterialComponent.RSButtonIconTwo();
        panel_application = new javax.swing.JPanel();
        pan_login = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnlogin = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();
        rSPanelImage3 = new rojerusan.RSPanelImage();
        jButton1 = new javax.swing.JButton();
        txtemail_login = new javax.swing.JTextField();
        txtclave_login = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pan_app = new javax.swing.JPanel();
        pan_home = new javax.swing.JPanel();
        rSPanelImage8 = new rojerusan.RSPanelImage();
        jLabel5 = new javax.swing.JLabel();
        btn_desconectar1 = new rojerusan.RSButtonMetro();
        panUserInfo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LblUserName = new javax.swing.JLabel();
        LblUserImage = new javax.swing.JLabel();
        LblUserLastName = new javax.swing.JLabel();
        LblUserEmail = new javax.swing.JLabel();
        LblUserRol = new javax.swing.JLabel();
        LblDevSOlogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LblDevUserName = new javax.swing.JLabel();
        LblDevPcName = new javax.swing.JLabel();
        LblDevSoName = new javax.swing.JLabel();
        pan_cmd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtconsola = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tddm4IoTbsDaemon");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(750, 550));

        pan_tittle.setBackground(new java.awt.Color(54, 103, 0));
        pan_tittle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pan_tittleMouseDragged(evt);
            }
        });
        pan_tittle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pan_tittleMousePressed(evt);
            }
        });

        btnclose.setBackground(new java.awt.Color(54, 103, 0));
        btnclose.setToolTipText("");
        btnclose.setBackgroundHover(new java.awt.Color(221, 37, 29));
        btnclose.setFocusable(false);
        btnclose.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnclose.setIconTextGap(3);
        btnclose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnclose.setMinimumSize(new java.awt.Dimension(10, 10));
        btnclose.setOpaque(true);
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        btnminimize.setBackground(new java.awt.Color(54, 103, 0));
        btnminimize.setToolTipText("");
        btnminimize.setBackgroundHover(new java.awt.Color(6, 0, 215));
        btnminimize.setFocusable(false);
        btnminimize.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnminimize.setIconTextGap(3);
        btnminimize.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_DROP_DOWN);
        btnminimize.setMinimumSize(new java.awt.Dimension(10, 10));
        btnminimize.setOpaque(true);
        btnminimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_tittleLayout = new javax.swing.GroupLayout(pan_tittle);
        pan_tittle.setLayout(pan_tittleLayout);
        pan_tittleLayout.setHorizontalGroup(
            pan_tittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_tittleLayout.createSequentialGroup()
                .addContainerGap(676, Short.MAX_VALUE)
                .addComponent(btnminimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pan_tittleLayout.setVerticalGroup(
            pan_tittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_tittleLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pan_tittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnminimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(pan_tittle, java.awt.BorderLayout.PAGE_START);

        panel_application.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 103, 0), 2));
        panel_application.setLayout(new java.awt.CardLayout());

        pan_login.setBackground(new java.awt.Color(255, 255, 255));
        pan_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 103, 0)));
        pan_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pan_login.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pan_loginMouseDragged(evt);
            }
        });
        pan_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pan_loginMousePressed(evt);
            }
        });
        pan_login.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnlogin.setBackground(new java.awt.Color(54, 103, 0));
        btnlogin.setText("Log In");
        btnlogin.setBorderPainted(false);
        btnlogin.setFont(new java.awt.Font("Cascadia Mono", 1, 10)); // NOI18N
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel1.setText("Sign in");

        rSPanelImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/resources/img/logoTdd.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage3Layout = new javax.swing.GroupLayout(rSPanelImage3);
        rSPanelImage3.setLayout(rSPanelImage3Layout);
        rSPanelImage3Layout.setHorizontalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        rSPanelImage3Layout.setVerticalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 204));
        jButton1.setText("Visit the Website");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        txtemail_login.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        jLabel7.setText("Passsword:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(rSPanelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(btnlogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtclave_login)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtemail_login, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(19, 19, 19))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addComponent(txtemail_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(txtclave_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan_login.add(jPanel5);
        jPanel5.setBounds(220, 50, 295, 337);

        panel_application.add(pan_login, "card4");

        pan_app.setPreferredSize(new java.awt.Dimension(650, 450));
        pan_app.setLayout(new java.awt.CardLayout());

        pan_home.setBackground(new java.awt.Color(245, 245, 245));
        pan_home.setForeground(new java.awt.Color(234, 236, 244));
        pan_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage8.setImagen(new javax.swing.ImageIcon(getClass().getResource("/resources/img/cloud.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage8Layout = new javax.swing.GroupLayout(rSPanelImage8);
        rSPanelImage8.setLayout(rSPanelImage8Layout);
        rSPanelImage8Layout.setHorizontalGroup(
            rSPanelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        rSPanelImage8Layout.setVerticalGroup(
            rSPanelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        pan_home.add(rSPanelImage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>Please wait while the web application<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;establishes a connection</html>");
        pan_home.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 330, -1));

        btn_desconectar1.setBackground(new java.awt.Color(100, 84, 115));
        btn_desconectar1.setText("Close Sesion");
        btn_desconectar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_desconectar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_desconectar1MouseClicked(evt);
            }
        });
        pan_home.add(btn_desconectar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 120, 30));

        panUserInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("USER INFORMATION");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panUserInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 150, 10));

        LblUserName.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        LblUserName.setText("ANTHONY ABRAHAN");
        panUserInfo.add(LblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 172, 10));

        LblUserImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panUserInfo.add(LblUserImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        LblUserLastName.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        LblUserLastName.setText("PACHAY ESPINOZA");
        panUserInfo.add(LblUserLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 160, 10));

        LblUserEmail.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        LblUserEmail.setForeground(new java.awt.Color(0, 102, 255));
        LblUserEmail.setText("anthony.pachay2017@uteq.edu.ec");
        panUserInfo.add(LblUserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 250, -1));

        LblUserRol.setBackground(new java.awt.Color(255, 255, 153));
        LblUserRol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblUserRol.setForeground(new java.awt.Color(255, 255, 255));
        LblUserRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblUserRol.setText("Moderador");
        LblUserRol.setOpaque(true);
        panUserInfo.add(LblUserRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 98, 22));

        LblDevSOlogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panUserInfo.add(LblDevSOlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 50, 50));

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("DEVICE INFORMATION");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panUserInfo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 240, 10));

        LblDevUserName.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        LblDevUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblDevUserName.setText("User: Tonyp");
        panUserInfo.add(LblDevUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 230, 10));

        LblDevPcName.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        LblDevPcName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblDevPcName.setText("PcName: ANBREZ");
        panUserInfo.add(LblDevPcName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 240, -1));

        pan_home.add(panUserInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 70));

        LblDevSoName.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        LblDevSoName.setForeground(new java.awt.Color(0, 102, 255));
        LblDevSoName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblDevSoName.setText("Windows");
        pan_home.add(LblDevSoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 172, 20));

        pan_cmd.setBackground(new java.awt.Color(255, 255, 255));
        pan_cmd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtconsola.setEditable(false);
        txtconsola.setColumns(20);
        txtconsola.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        txtconsola.setRows(5);
        jScrollPane1.setViewportView(txtconsola);

        pan_cmd.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 710, 310));

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Command Window:");
        pan_cmd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pan_home.add(pan_cmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 730, 350));

        pan_app.add(pan_home, "card2");

        panel_application.add(pan_app, "card2");

        getContentPane().add(panel_application, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pan_loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_loginMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_pan_loginMousePressed

    private void pan_loginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_loginMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_pan_loginMouseDragged

    private void pan_tittleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_tittleMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pan_tittleMousePressed

    private void pan_tittleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_tittleMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_pan_tittleMouseDragged

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        if (ws != null) {
            ws.closeWebSocket();
        }
        System.exit(0);
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnminimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizeActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_btnminimizeActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        email = txtemail_login.getText();
        String pwd = txtclave_login.getText();

        if (email.trim().length() > 0 && pwd.trim().length() > 0) {
            btnlogin.setEnabled(false);
            txtclave_login.setText("");
            if (Dao.LogIn(email, pwd)) {
                pan_app.setVisible(true);
                pan_login.setVisible(false);

                pan_home.setVisible(true);
                pan_cmd.setVisible(false);

                //load info in panel
                loadData();

                ws = new WsCliente(email);
//                ws.setMiform(this);
                ScopeApp.setMainForm(this);
            }
            btnlogin.setEnabled(true);
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        BrowserClass.abrirNavegadorPorDefecto(DataStatic.getApplicationURL());
    }//GEN-LAST:event_jButton1MouseClicked

    public void conectedWs(boolean flag) {
        //pan_home.setVisible(!flag);
        jLabel5.setVisible(!flag);
        rSPanelImage8.setVisible(!flag);
        pan_cmd.setVisible(flag);
    }
    private void btn_desconectar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_desconectar1MouseClicked
        // TODO add your handling code here:
        System.out.println("Estado Socker:" + ScopeApp.getWsClient() != null);
        if (ScopeApp.getWsClient() != null) {
            ScopeApp.getWsClient().closeWebSocket();
        }
        ScopeApp.setDataUser(null);
        ScopeApp.setWsClient(null);
        pan_app.setVisible(false);
        pan_login.setVisible(true);
    }//GEN-LAST:event_btn_desconectar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblDevPcName;
    private javax.swing.JLabel LblDevSOlogo;
    private javax.swing.JLabel LblDevSoName;
    private javax.swing.JLabel LblDevUserName;
    private javax.swing.JLabel LblUserEmail;
    private javax.swing.JLabel LblUserImage;
    private javax.swing.JLabel LblUserLastName;
    private javax.swing.JLabel LblUserName;
    private javax.swing.JLabel LblUserRol;
    private rojerusan.RSButtonMetro btn_desconectar1;
    private RSMaterialComponent.RSButtonIconTwo btnclose;
    private rojerusan.RSMaterialButtonRectangle btnlogin;
    private RSMaterialComponent.RSButtonIconTwo btnminimize;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panUserInfo;
    private javax.swing.JPanel pan_app;
    public javax.swing.JPanel pan_cmd;
    public javax.swing.JPanel pan_home;
    private javax.swing.JPanel pan_login;
    private javax.swing.JPanel pan_tittle;
    private javax.swing.JPanel panel_application;
    private rojerusan.RSPanelImage rSPanelImage3;
    private rojerusan.RSPanelImage rSPanelImage8;
    private javax.swing.JPasswordField txtclave_login;
    public javax.swing.JTextArea txtconsola;
    private javax.swing.JTextField txtemail_login;
    // End of variables declaration//GEN-END:variables
}
